# -*- coding: utf-8 -*-

require 'paper_house'

include PaperHouse::DSL

libhello = shared_library_task :libhello do |task|
  task.version = '0.1.0'
  task.sources = 'hello.c'
  task.library_dependencies = 'm' # not used.
end

executable_task :hello => [:libhello] do |task|
  task.sources = 'main.c'
end
