# -*- coding: utf-8 -*-

require 'paper_house'

include PaperHouse::DSL

executable_task :hello do | task |
  task.executable_name = 'hello'
  task.target_directory = 'objects'
  task.sources = FileList['sources/*.c']
  task.includes = 'includes'
  task.cflags = %w(-Wall -Wextra)
end
