# -*- coding: utf-8 -*-

require 'paper_house'

include PaperHouse::DSL

static_library_task :libhello do | task |
  task.library_name = 'hello'
  task.target_directory = 'objects'
  task.sources = 'sources/hello.c'
  task.includes = 'includes'
  task.cflags = %w(-Werror -Wall -Wextra)
end

executable_task :hello => :libhello do | task |
  task.sources = 'sources/main.c'
  task.includes = 'includes'
end
