# -*- coding: utf-8 -*-

require 'paper_house'

include PaperHouse::DSL

static_library_task :libhello do | task |
  task.sources = 'hello.c'
end

executable_task :hello => :libhello do | task |
  task.sources = 'main.c'
end
